#!/usr/bin/env dash

# main menu to access instantASSIST

ASSIST=$(cat /usr/share/instantassist/cache/cache | instantmenu -i -p instantASSIST -n -h 32 -F -ct | grep -o '^.')

[ -z "$ASSIST" ] && exit

if [ -d /usr/share/instantassist/assists/"$ASSIST" ]; then
    ASSIST2="$(instantmenu -i -p instantASSIST -n -h 32 -F -ct </usr/share/instantassist/cache/"$ASSIST"/cache | grep -o '^.')"
    [ -z "$ASSIST2" ] && exit
    SCRIPTPATH=/usr/share/instantassist/assists/"$ASSIST/$ASSIST2"
else
    if ! [ -e /usr/share/instantassist/assists/"$PAPERAPP" ]; then
        echo "assist not found"
        exit
    fi
    SCRIPTPATH=/usr/share/instantassist/assists/"$ASSIST"
fi

"${SCRIPTPATH}.sh"
