#!/usr/bin/env dash
# main menu to access instantASSIST

PAPERAPP=$(cat /usr/share/instantassist/menus/apps | instantmenu -i -p instantASSIST -n -h 32 -F)
[ -z "$PAPERAPP" ] && exit

TEMP=$(ls /usr/share/instantassist/menus/dm/$PAPERAPP*.sh | sed 's/^.*\///g' |
    grep -o '^[^\.]*' | grep "^$PAPERAPP" | grep -o '.$' | uniq)

exescript() {
    [ -e /usr/share/instantassist/menus/dm/$1.sh ] &&
        echo "executing $1" &&
        bash /usr/share/instantassist/menus/dm/$1.sh && exit
}

if [ -n "$TEMP" ] && [ "$(echo "$TEMP" | wc -l)" -gt "1" ]; then
    if [ -e /usr/share/instantassist/menus/dm/$PAPERAPP$PAPERAPP.sh ]; then
        APP2=$(echo "$TEMP" | instantmenu -i -n -h 32 -F)
    else
        APP2=$(echo "$TEMP" | instantmenu -i -n -h 32 -F)
    fi

    if [ -n "$APP2" ]; then
        exescript "$PAPERAPP$APP2"
    else
        exescript "$PAPERAPP$PAPERAPP"
        exescript "$PAPERAPP"
    fi
else
    exescript "$PAPERAPP$PAPERAPP"
    exescript "$PAPERAPP"
fi
