#!/usr/bin/env dash
# the main script for starting and accessing my dmenus
PAPERAPP=$(cat ~/paperbenni/menus/apps | dmenu -n -h 32 -F)
[ -z "$PAPERAPP" ] && exit
[ -e ~/paperbenni/menus/dm/$PAPERAPP.sh ] &&
    bash ~/paperbenni/menus/dm/$PAPERAPP.sh
